services:
  - type: web
    name: luckyjet-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python luckyjet_masterbot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
